version: '3.4'

services:
  server:
    image: mcr.microsoft.com/dotnet/core/samples:aspnetapp
    ports:
      - 80
      - 433
    environment:
      ASPNETCORE_URLS: "https://+:443;http://+:80"      
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "Pa55w0rd!"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/nolowa.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
  
  # db:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   user: root
  #   ports:
  #     - "1433:1433"
  #   environment:
  #     ACCEPT_EULA: Y
  #     SA_PASSWORD: my_passw0rd!1
  
  # cache:
  #   image: redis
  #   ports:
  #     - "6379:6379"

