version: "3.4"

services:
  server:
    build: .
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "5001"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "Pa55w0rd!"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/nolowa.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
     - db
     - directMessageCache
     - postCache
     - searchCache
  
  db:
    image: mcr.microsoft.com/mssql/server:latest
    user: root
    ports:
      - "1433:1433"    
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: my_passw0rd!1
    volumes:
      - ./sqldata:/var/opt/mssql/data
  
  directMessageCache:
    image: redis
    ports:
      - "5060:6379"

  postCache:
    image: redis
    ports:
      - "5061:6379"

  searchCache:
    image: redis
    ports:
      - "5062:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-local
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "RabbitMQ-My-Cookies"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "asdf1234"