version: "3.4"

services:
  server:
    build: .
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "5001"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "Pa55w0rd!"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/nolowa.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - db
      - cache
  
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "my_passw0rd!1"
  
  cache:
    image: redis
    ports:
      - "6379:6379"

